### ISSUE TITLE
.id columns should be built from slack timestamps

### ISSUE THREAD

**Issue by zfogg** [hackclub/sb2#5]
maybe `Message.id`'s column type signature should be `[message_ts, thread_ts=0]`.

sometimes internet / heroku lag makes messages come in slow. i don't think slack guarantees any particular ordering to how messages get delivered either. so messages may come late, in bursts, and they may be out of order.

right now i'm just letting postgres set the `.created` column and using a sequential integer `.id`. this is usually fine and we really only use bunyan for rough estimates anyway.

HOWEVER, each slack message already comes with a unique identifier. we could use each slack message's message_ts (with optional thread_ts) as the unique identifier.

this will give us exact stats rather than approximations almost for free.

**Comment by zfogg** [comment]
of course this applies to `Reaction.id` as well.

**Comment by maxwofford** [comment]
Closing this as [the repo is deprecated](https://github.com/hackclub/bunyan/commit/ab74d1b97d3d7d41b7391f7d9e6c8a87ef9e4a15)!
